In [ ]:
# RUN THIS COMMAND ONLY IF YOU USE GOOGLE COLAB.
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# RUN THIS COMMAND ONLY IF YOU USE GOOGLE COLAB.
%cd drive/MyDrive/TechLabs/02_Data\ Manipulation/Part\ B\ -\ Numpy

In [1]:
# ALWAYS IMPORT NUMPY FIRST.
import numpy as np

# Chapter 1 - List vs. Array in Python
### Hey Techie,   
Welcome to the first notebook of this Numpy tutorial series. We encourage you to take this notebook as a template to code along the instruction video, which you may find at: https://youtu.be/OVD26YMkT_c. Today's video explains the differences between built-in lists in Python and Numpy arrays. In the end, please try to solve the presented tasks. In case you are interested, you find a complete walk through the tasks at: https://youtu.be/mkbgEvUkSaM. 

#### Have fun! :-)   
*Video length in total*: 15 minutes   
*Self-study time*: 15 minutes   
*Total*: **30 minutes**   
#### Credits
Complete Python Numpy Tutorial for Beginners, Nate at StrataScratch, https://www.youtube.com/channel/UCW8Ews7tdKKkBT6GdtQaXvQ.
<hr style="border:2px solid gray"> </hr>   

# Intro to NumPy (Numerical Python)

NumPy is the fundamental package for scientific computing in Python. NumPy is used in many other packages in python even though you may not see it explicitly running in your code.

It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.




## Lists in Python

- Natively built into python and doesn't require you to import libraries to use the functionality
- Lists are great to store values collectively and retrieve data easily

#### We can create list of integers

In [4]:
#manual way of creating lists
A = [10, 11, 12, 13, 14]

In [9]:
#create lists using functions
L = list(range(0, 10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
#find the data type of a list
type(L[0])

int

#### We can create a list of strings

In [11]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
type(L2[0])

str

#### We can create heterogeneous lists

In [13]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Arrays in Python

What is an array?

- An array is a data structure that allows you to store values...like a list

How is it different than a list?
- An array is more efficient at storing large amounts of data
- Easy and simple to perform numerical/math operations

### Creating Arrays From Python Lists

#### Use np.array to create arrays from Python lists

In [14]:
# integer array
listA = [1,4,2,5,3]
numpyarrayA = np.array(listA)
numpyarrayA

array([1, 4, 2, 5, 3])

#### Numpy is constrained to arrays that all contain the same type. If the types do not match, NumPy will try to change the data type

In [30]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

#### Numpy allows you to make multidimensional arrays using lists of lists

In [40]:
np.array([[1, 2, 3], 
          [3, 4],
          [3, 3]])

/var/folders/wv/4ykr26xn1xz7lvsm_2btgjc00000gn/T/ipykernel_1134/3111710656.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2, 3],


array([list([1, 2, 3]), list([3, 4]), list([3, 3])], dtype=object)

<hr style="border:2px solid gray"> </hr>   

## Practice Tasks

#### 1. Create a list containing the values 1, 3, and 5.

In [21]:
# START YOUR CODE HERE.
l = [1, 3, 5]
l

[1, 3, 5]

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>[1, 3, 5]</code>
</p>
</details> 

#### 2. Create a list containing the values from 0 to 9 using the range function and assign it to *L*.

In [20]:
# START YOUR CODE HERE.
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>L = list(range(10))</code>
</p>
</details> 

#### 3. Print the first element from *L*.

In [24]:
# START YOUR CODE HERE.
print(l[0])


1


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print(L[0])</code>
</p>
</details> 

#### 4. Create an array containing the values [5, 4, 3, 2, 1] and store is in *A*.

In [31]:
# START YOUR CODE HERE.
A = ([5,4,3,2,1])
numpyarrayA = np.array(A)
numpyarrayA

array([5, 4, 3, 2, 1])

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>A = np.array([5, 4, 3, 2, 1])</code>
</p>
</details> 

#### 5. Print the datatype of array *A*.

In [34]:
# START YOUR CODE HERE.
# type(numpyarrayA)

numpyarrayA.dtype

dtype('int64')

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print(A.dtype)</code>
</p>
</details> 

#### 6. What is the expected datatype of this array? Why? Enter the expected datatype between quotation marks

In [36]:
# A2 = np.array([3.14, 4, 2, 3])
# # START YOUR CODE HERE.
# A2.dtype == 'float'

A2.dtype

dtype('float64')

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>A2.dtype == 'float64'</code>
</p>
</details> 

#### 7. For practice reasons, create a multidimesional array from a multidimesional list. 

In [39]:
# START YOUR CODE HERE.

np.array([[1,2,3],
[4,5,6],
[7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code># EXAMPLE</code><br />
    <code>array = np.array([[1, 2], [3, 4], [5, 6]])</code>
</p>
</details>