In [ ]:
# RUN THIS COMMAND ONLY IF YOU USE GOOGLE COLAB.
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# RUN THIS COMMAND ONLY IF YOU USE GOOGLE COLAB.
%cd drive/MyDrive/TechLabs/02_Data\ Manipulation/Part\ B\ -\ Numpy

In [2]:
# ALWAYS IMPORT NUMPY FIRST.
import numpy as np

# Chapter 7 - Arithmetic Operators on Arrays using NumPy
### Hey Techie,   
Welcome to the seventh notebook of this Numpy tutorial series. We encourage you to take this notebook as a template to code along the instruction video, which you may find at: https://youtu.be/JZfsZuLKaJ4. Today's video explains how to apply different arithmetic operations on Numpy arrays. In the end, please try to solve the presented tasks. In case you are interested, you find a complete walk through the tasks at: https://youtu.be/ccDPI7v-0QE. 

#### Have fun! :-)   
*Video length in total*: 26 minutes   
*Self-study time*: 26 minutes   
*Total*: **52 minutes**   
#### Credits
Complete Python Numpy Tutorial for Beginners, Nate at StrataScratch, https://www.youtube.com/channel/UCW8Ews7tdKKkBT6GdtQaXvQ.
<hr style="border:2px solid gray"> </hr>   

# Computation on NumPy Arrays: Universal Functions

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; in the next few sections, we will dive into the reasons that NumPy is so important in the Python data science world.
Namely, it provides an easy and flexible interface to optimized computation with arrays of data.

Computation on NumPy arrays can be very fast, or it can be very slow.
The key to making it fast is to use *vectorized* operations, generally implemented through NumPy's *universal functions* (ufuncs).
This section motivates the need for NumPy's ufuncs, which can be used to make repeated calculations on array elements much more efficient.
It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.

Vectorized operations in NumPy are implemented via *ufuncs*, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.
Ufuncs are extremely flexible – before we saw an operation between a scalar and an array, but we can also operate between two arrays:

In [4]:
import numpy as np

In [6]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

And ufunc operations are not limited to one-dimensional arrays–they can also act on multi-dimensional arrays as well:

In [11]:
x = np.arange(9).reshape((3, 3))
print(x)
2 ** x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

## Exploring NumPy's UFuncs

Ufuncs exist in two flavors: *unary ufuncs*, which operate on a single input, and *binary ufuncs*, which operate on two inputs.
We'll see examples of both these types of functions here.

### Array arithmetic

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.
The standard addition, subtraction, multiplication, and division can all be used:

In [12]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division, rounding off

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


There is also a unary ufunc for negation, and a ``**`` operator for exponentiation, and a ``%`` operator for modulus:

In [13]:
# negation
print("-x     = ", -x)

# exponent
print("x ** 2 = ", x ** 2)

# modulus
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In addition, these can be strung together however you wish, and the standard order of operations is respected:

In [ ]:
-(0.5*x + 1) ** 2 

Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; for example, the ``+`` operator is a wrapper for the ``add`` function:

In [14]:
np.add(x, 2)

array([2, 3, 4, 5])

The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


### Absolute value

Just as NumPy understands Python's built-in arithmetic operators, it also understands Python's built-in absolute value function:

In [15]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

The corresponding NumPy ufunc is ``np.absolute``, which is also available under the alias ``np.abs``:

In [16]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [17]:
np.abs(x)

array([2, 1, 0, 1, 2])

This ufunc can also handle complex data, in which the absolute value returns the magnitude:

In [18]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Trigonometric functions

NumPy provides a large number of useful ufuncs, and some of the most useful for the data scientist are the trigonometric functions.
We'll start by defining an array of angles:

In [22]:
theta = np.linspace(0, np.pi, 3)

Now we can compute some trigonometric functions on these values:

In [24]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


The values are computed to within machine precision, which is why values that should be zero do not always hit exactly zero.
Inverse trigonometric functions are also available:

In [25]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the exponentials:

In [3]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available.
The basic ``np.log`` gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:

In [4]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


There are also some specialized versions that are useful for maintaining precision with very small input:

In [ ]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

When ``x`` is very small, these functions give more precise values than if the raw ``np.log`` or ``np.exp`` were to be used.

<hr style="border:2px solid gray"> </hr>   

## Practice Tasks   

#### 1. Add 2 to every element in *x*, subtract 2 from every element in *x*, multiply every element in *x* with 3.

In [5]:
x = np.arange(9)
# INSERT CODE BELOW.
print("Add 2:", x + 1)
print("Subtract 2:", x - 2)
print("Multiply 3:", x * 3)

Add 2: [1 2 3 4 5 6 7 8 9]
Subtract 2: [-2 -1  0  1  2  3  4  5  6]
Multiply 3: [ 0  3  6  9 12 15 18 21 24]


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print("Add 2:", x+2)</code><br />
    <code>print("Subtract 2:", x-2)</code><br />
    <code>print("Multiply 3:", x*3)</code>
</p>
</details>

#### 2. Negate every element in *x*, cube every element in *x*, calcualte the remainder if you divide every element by 4 in *x*.

In [8]:
# INSTERT CODE BELOW.
print("Negation:", -1*x)
print("Cubed:", x ** 3)
print("Mod 4:", x % 4)

Negation: [ 0 -1 -2 -3 -4 -5 -6 -7 -8]
Cubed: [  0   1   8  27  64 125 216 343 512]
Mod 4: [0 1 2 3 0 1 2 3 0]


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print("Negation:", -1*x)</code><br />
    <code>print("Cubed:", x**3)</code><br />
    <code>print("Mod 4:", x%4)</code>
</p>
</details>

#### 3. Print the absolute value for every element in *x*.

In [10]:
x = np.arange(-4, 5)
# START YOUR CODE HERE.
np.abs(x)

array([4, 3, 2, 1, 0, 1, 2, 3, 4])

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>np.abs(x)</code>
</p>
</details>

#### 4. Print the results sine, cosine, and tangent on the elements of *theta*.

In [11]:
theta = np.linspace(0, np.pi, 3)
# INSERT CODE BELOW.
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print("sin(theta) = ", np.sin(theta))</code><br />
    <code>print("cos(theta) = ", np.cos(theta))</code><br />
    <code>print("tan(theta) = ", np.tan(theta))</code>
</p>
</details>

#### 5. Print the results arcsine, arccosine, and arctangent on the elements of *x*.

In [12]:
x = [-1, 0, 1]
# INSERT CODE BELOW.
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print("arcsin(x) = ", np.arcsin(x))</code><br />
    <code>print("arccos(x) = ", np.arccos(x))</code><br />
    <code>print("arctan(x) = ", np.arctan(x))</code>
</p>
</details>

#### 6. Print the results of e^x, 2^x, and 5^x.

In [13]:
x = [1, 2, 3]
# INSERT CODE BELOW.
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("5^x   =", np.power(5, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
5^x   = [  5  25 125]


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print("e^x =", np.exp(x))</code><br />
    <code>print("2^x =", np.exp2(x))</code><br />
    <code>print("5^x =", np.power(5, x))</code>
</p>
</details>

#### 7. Print the results of ln, log 2, and log 10 on x.

In [14]:
x = [1, 2, 4, 10]
# INSERT CODE BELOW.
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print("ln(x) =", np.log(x))</code><br />
    <code>print("log2(x) =", np.log2(x))</code><br />
    <code>print("log10(x) =", np.log10(x))</code>
</p>
</details>


#### 8. Print the results of exp(z) - 1 and expm1(z) to see that expm1 is more precise.

In [16]:
z = [0, 0.0000000001, 0.000000001, 0.00000001]
# INSERT CODE BELOW.
print("exp(z) - 1 =", np.expm1(z))
print("expm1(z) =", np.expm1(z))

exp(z) - 1 = [0.00000000e+00 1.00000000e-10 1.00000000e-09 1.00000001e-08]
expm1(z) = [0.00000000e+00 1.00000000e-10 1.00000000e-09 1.00000001e-08]


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Solution (click to expand)</b></font>
</summary>
<p>
    <code>print("(e^z)-1 =", np.exp(z)-1)</code><br />
    <code>print("(e^z)-1 =", np.expm1(z))</code><br />
</p>
</details>